- name: "users | create"
  user: name={{ user }} shell=/bin/bash

- name: "users | copy authorized key"
  shell: "mkdir -p {{ home }}/.ssh -m 700 && cp /root/.ssh/authorized_keys {{ home }}/.ssh && chown -R {{ user }}:{{ user }} {{ home }}/.ssh"

- name: 'users | nopasswd'
  shell: "gpasswd -a {{ user }} sudo"

- name: "users | touch permissions"
  file: path=/etc/sudoers.d/{{ user }} state=touch

- name: "users | write permissions"
  lineinfile: dest=/etc/sudoers.d/{{ user }} state=present regexp="^" line="deploy ALL=(ALL) NOPASSWD:ALL"

